### ISSUE TITLE
Problem with MemoryArray concept for array<T const>

### ISSUE THREAD

**Issue by mmorale3** [TRIQS/nda#28] opened 2022-11-17 17:57 UTC
### Prerequisites

* Please check that a similar issue isn't already filed: https://github.com/issues?q=is%3Aissue+user%3Atriqs

### Description

array<const T, N> doesn't satisfy MemoryArray concept.

The problem is in the definition of the MemoryArray concept:

/// Check if A is an Array and exposes its `data()` and its `indexmap().strides()`
template <typename A>
concept MemoryArray = Array<A> && requires(A &a) {

  // We can acquire the pointer to the underlying data
  { a.data() } -> std::same_as<std::conditional_t<std::is_const_v<A>, const get_value_t<A>, get_value_t<A>> *>;

  // Exposes the memory stride for each dimension
  { a.indexmap().strides() } -> StdArrayOfLong;
};

 { a.data() } -> std::same_as<std::conditional_t<std::is_const_v<A>, const get_value_t<A>, get_value_t<A>> *>;

will fail for any array/array_view<const T> since get_value_t decays away qualifiers.

### Additional Information

Error message from gcc 11,2

.../c++/nda/concepts.hpp:103:35:   in requirements with 'A& a' [with A = nda::basic_array_view<const double, 2, nda::C_layout, 'A', nda::default_accessor, nda::borrowed>]
.../c++/nda/concepts.hpp:106:11: note: 'a.data()' does not satisfy return-type-requirement, because
  106 |   { a.data() } -> std::same_as<std::conditional_t<std::is_const_v<A>, const get_value_t<A>, get_value_t<A>> *>;
      |     ~~~~~~^~
.../c++/nda/concepts.hpp:106:5: error: deduced expression type does not satisfy placeholder constraints
  106 |   { a.data() } -> std::same_as<std::conditional_t<std::is_const_v<A>, const get_value_t<A>, get_value_t<A>> *>;
      |   ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by Wentzell** [comment] 2022-11-17 18:56
This should be fixed in commits 328cdfd and a9760b1, which were also applied to DEV_H5SLAB. Please confirm that the issue is resolved

**Comment by Wentzell** [comment] 2022-12-20 19:05
Closing this, as it was fixed.

**Closed as completed by Wentzell** 2022-12-20 19:05 UTC
Labels: bug
